# Generated by Django 4.0.3 on 2022-03-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Image_flag',
        ),
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
