# Generated by Django 4.0.3 on 2022-03-24 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_image_flag_alter_user_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
