# Generated by Django 4.0.3 on 2022-03-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
